name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Install dependencies
      run: npm install
      working-directory: ./src

    - name: Create .env file
      run: |
        echo "VITE_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" > src/.env
        echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> src/.env
        echo "VITE_FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> src/.env
        echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> src/.env
        echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> src/.env
        echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> src/.env
        echo "VITE_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> src/.env
        echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> src/.env
        echo "VITE_SERVER_URL=${{ secrets.PROD_SERVER_URL }}"
      
    - name: Build project 
      run: npm run build
      working-directory: ./src

    - uses: FirebaseExtended/action-hosting-deploy@v0
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAT_TRANSSOCIAL_TEST }}
        channelId: live
        projectId: chat-transsocial-test
